language: java
jdk: oraclejdk8

before_install:
  - pip install --user codecov

after_success:
  - codecov
# ./gradlew sonarqube -Dsonar.organization=sleepy-weasel -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
