language: java
jdk: oraclejdk8

sudo: required

services:
  - docker

before_install:
  - export TEST_DATABASE_NAME=rekolekcjedb-test
  - export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/${TEST_DATABASE_NAME}
  - export SPRING_DATASOURCE_PASSWORD=mysecretpassword
  - docker run --name db-rekolekcje-test -p 5433:5432 -e POSTGRES_DB=${TEST_DATABASE_NAME} -e POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD} -d postgres

addons:
  chrome: stable
#  sonarcloud:
#    organization: "oaza-waw"

script:
  - ./gradlew sonarqube -Dsonar.organization=oaza-waw -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

cache:
  bundler: true
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
