language: java
jdk: oraclejdk8

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu

after_script:
  - ./gradlew sonarqube -Dsonar.organization=oaza-waw -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    - 'rekolekcje-webapp/node_modules'
