server:
 port: ${PORT:5000}

spring:

  profiles:
    active: test-local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/rekolekcjedb-test
    username: postgres
    password: postgres

jwt:
  header: Authorization
  secret: mySecretForTests
  expiration: 604800
  route:
    authentication:
      path: api/auth
      refresh: api/refresh
