server:
 port: ${PORT:5000}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:rekolekcje_test_db;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
    url: jdbc:postgresql://localhost:5433/rekolekcjedb-test
    username: postgres
    password: mysecretpassword

liquibase:
  change-log: classpath:/db/master-changelog.xml

jwt:
  header: Authorization
  secret: mySecretForTests
  expiration: 604800
  route:
    authentication:
      path: api/auth
      refresh: api/refresh
