server:
  port: 5000

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rekolekcjedb
    username: postgres
    password: postgres

liquibase:
  change-log: classpath:/pl.oaza.warszawa.dor.rekolekcje/changelogs.groovy

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
