# IMPORTANT!
# This file is meant to serve only as an example of local configuration
# If you want to change default application configuration, please copy this file
# and save as application-local.yml
# This *local* file will be ignored from VCS and you can keep your overrides there

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:rekolekcjedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: postgres
