server:
  port: ${PORT:5000}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

liquibase:
  change-log: classpath:/pl.oaza.warszawa.dor.rekolekcje/changelogs.xml

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: api/auth
      refresh: api/refresh
